server:
  port: 8082

spring:
  application:
    name: DEP-SVC
  zipkin:
    base-url: http://127.0.0.1:9411/


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0.eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka