apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
  labels:
    app: cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      containers:
        - name: department-service-app
          image: venkat7010/cloud-config-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9296

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
spec:
  selector:
    app: cloud-config-server
  ports:
    - port: 80
      targetPort: 9296


