apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
        - name: department-service-app
          image: venkat7010/department-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: department-service-app
spec:
  selector:
    app: department-service-app
  ports:
    - port: 80
      targetPort: 8082


