apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-app
  labels:
    app: employee-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service-app
  template:
    metadata:
      labels:
        app: employee-service-app
    spec:
      containers:
        - name: employee-service-app
          image: venkat7010/employee-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: employee-service-app
spec:
  selector:
    app: employee-service-app
  ports:
    - port: 80
      targetPort: 8081


